service: synk # NOTE: Don't put the word "google" in here

frameworkVersion: ">1.12.0 <2.0.0"

provider:
  name: google
  memorySize: 128
  timeout: 60s
  runtime: nodejs
  project: asdf-165014
  # the path to the credentials file needs to be absolute
  credentials: ${env:HOME}/.gcloud/gcloud-service-key.json

plugins:
  - serverless-google-cloudfunctions

# needs more granular excluding in production as only the serverless provider npm
# package should be excluded (and not the whole node_modules directory)
package:
  exclude:
    - node_modules/**
    - .gitignore
    - package.json
    - .git/**

functions:
  first:
    handler: http
    events:
      - http: path
