service: synk

provider:
  name: google
  runtime: nodejs
  project: ${env:PROJECT}
  credentials: ${file(./home.js):theGoogleCloudCredentialFile}

plugins:
  - serverless-google-cloudfunctions

functions:
  first:
    handler: http
    events:
      - http: path
